# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6989407a6bf8996b43afa304fc55fce2775b233090156f41aeb15ac0fc2fb283a779e28ba4db5c2a5f220a6c7fbdcf310556474a49200d03c37c6c2855d25fd1

test:
  secret_key_base: e161a5c3f746d207d861842d2251c56d17148671fdabdf24cf076a87c4e4ceebae68ec69bddaf8b26558cb8d32396c330fd453d39ba6ad3ca0a61d342456d141

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
